# This is a basic workflow to help you get started with Actions

name: Manual trigger debian rootfs setup
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      arch:
        description: "Debian Architecture"
        required: true
        default: "amd64"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install multistrap binfmt-support qemu-user-static debian-archive-keyring
          sudo modprobe binfmt_misc
          sudo apt-key add /usr/share/keyrings/debian-archive-keyring.gpg
          
      - name: Run setup.sh
        run: |
          chmod +777 setup.sh
          sudo bash setup.sh ${{ github.event.inputs.arch }}
          echo "OUTPUT=$build_dir/$tar_name" >> $GITHUB_ENV
        
      - name: Upload debian-rootfs
        uses: actions/upload-artifact@v2
        with:
          name: debian-rootfs-${{ github.event.inputs.arch }}
          path: $OUTPUT
