# This is a basic workflow to help you get started with Actions

name: debian-rootfs GitHub CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      codename:
        description: "Debian codename"
        required: true
        default: "bullseye"
      
      arch:
        description: "Debian Architecture"
        required: true
        default: "amd64"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Etc/GMT

      - name: Get current time
        uses: srfrnk/current-time@master
        id: current-time
        with:
          format: YYYY-MM-DD-HH-mm-ss
        
      - name: Set arch for qemu
        run: |
          ARCH=${{ github.event.inputs.arch }}
          if [ "$ARCH" == "amd64" ]
          then
             ARCH=x86_64
          elif [ "$ARCH" == "arm64" ]
          then
             ARCH=aarch64
          else
             ARCH=${{ github.event.inputs.arch }}
          fi
          printenv ARCH

      # Install required packages
      - name: Install required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y debootstrap qemu qemu-user qemu-user-static binfmt-support binutils

      # Runs a set of commands using the runners shell
      - name: First part - Download and Install core packages
        run: |
          mkdir debian-rootfs-${{ steps.current-time.outputs.formattedTime }}
          sudo debootstrap --foreign --arch ${{ github.event.inputs.arch }} ${{ github.event.inputs.codename }} ./debian-rootfs-${{ steps.current-time.outputs.formattedTime }}
          
      - name: Second part of the setup
        run: |
          cp /usr/bin/qemu-'$ARCH'-static ./debian-rootfs-${{ steps.current-time.outputs.formattedTime }}/usr/bin
          LANG=C.UTF-8 sudo chroot debian-rootfs-${{ steps.current-time.outputs.formattedTime }} /usr/bin/qemu-'$ARCH'-static /bin/bash /usr/bin/chfn -f "systemd Time Synchronization" /debootstrap/debootstrap --second-stage exit
          
      - name: Archive the rootfs
        run: sudo tar -cpvzf debian-rootfs-${{ steps.current-time.outputs.formattedTime }}.tar.gz debian-rootfs-${{ steps.current-time.outputs.formattedTime }}
          
      - name: Upload debian-rootfs
        uses: actions/upload-artifact@v2
        with:
          name: debian-rootfs-${{ steps.current-time.outputs.formattedTime }}
          path: debian-rootfs-${{ steps.current-time.outputs.formattedTime }}.tar.gz
          
