# This is a basic workflow to help you get started with Actions

name: Manual trigger debian rootfs setup
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      arch:
        description: "Debian Architecture"
        required: true
        default: "amd64"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends multistrap binfmt-support qemu-user-static debian-archive-keyring
          sudo modprobe binfmt_misc
          sudo tee /usr/share/keyrings/debian-archive-keyring.gpg 
          sudo apt-get update

      - name: Run setup.sh
        run: |
          sudo apt-get install wget proot -y && hash -r && wget "https://raw.githubusercontent.com/EXALAB/AnLinux-Resources/master/Rootfs/Debian/amd64/debian-rootfs-amd64.tar.xz" && mkdir debian-rootfs && tar -xJf debian-rootfs-amd64.tar.xz -C debian-rootfs
          ./debstart.sh
          apt-get update && apt-get upgrade
          apt-get install -y multistrap binfmt-support qemu-user-static debian-archive-keyring
          modprobe binfmt_misc
          set -xe
          chmod +777 setup.sh
          bash setup.sh ${{ github.event.inputs.arch }}
          exit
          echo "OUTPUT=$build_dir/debian-fs/root/debian-rootfs-${{ github.event.inputs.arch }}.tar" >> $GITHUB_ENV
        
      - name: Upload debian-rootfs
        uses: actions/upload-artifact@v2
        with:
          name: debian-rootfs-${{ github.event.inputs.arch }}
          path: $OUTPUT
