# This is a basic workflow to help you get started with Actions

name: Push-builds

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y debootstrap binfmt-support qemu-user-static debian-archive-keyring
          sudo modprobe binfmt_misc
          #sudo tee /usr/share/keyrings/debian-archive-keyring.gpg 
          sudo apt-get update

      - name: Run setup-debootstrap.sh
        run: |
          sudo chmod +x setup-debootstrap.sh
          sudo bash -x setup-debootstrap.sh --arch amd64
          sudo bash -x setup-debootstrap.sh --arch i386
          sudo bash -x setup-debootstrap.sh --arch arm64
          sudo bash -x setup-debootstrap.sh --arch armel
          sudo bash -x setup-debootstrap.sh --arch armhf
          sudo bash -x setup-debootstrap.sh --arch mips64el
          #OUTPUT=$(sudo find "./build/amd64/" -maxdepth 1 -name "*.tar.gz" | grep -q -H 'debian-rootfs-amd64-')
          #echo "OUTPUT=$(echo $OUTPUT)" >> $GITHUB_ENV

      - name: Upload debian-rootfs-amd64
        uses: actions/upload-artifact@v2
        with:
          name: debian-rootfs-amd64
          path: ./build/amd64/*.tar.gz

      - name: Upload debian-rootfs-i386
        uses: actions/upload-artifact@v2
        with:
          name: debian-rootfs-i386
          path: ./build/i386/*.tar.gz

      - name: Upload debian-rootfs-arm64
        uses: actions/upload-artifact@v2
        with:
          name: debian-rootfs-arm64
          path: ./build/arm64/*.tar.gz

      - name: Upload debian-rootfs-armel
        uses: actions/upload-artifact@v2
        with:
          name: debian-rootfs-armel
          path: ./build/armel/*.tar.gz

      - name: Upload debian-rootfs-armhf
        uses: actions/upload-artifact@v2
        with:
          name: debian-rootfs-armhf
          path: ./build/armhf/*.tar.gz

      - name: Upload debian-rootfs-mips64el
        uses: actions/upload-artifact@v2
        with:
          name: debian-rootfs-mips64el
          path: ./build/mips64el/*.tar.gz
