# This is a basic workflow to help you get started with Actions

name: Push-builds

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-amd64:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y debootstrap binfmt-support qemu-user-static debian-archive-keyring
          sudo modprobe binfmt_misc
          #sudo tee /usr/share/keyrings/debian-archive-keyring.gpg 
          sudo apt-get update

      - name: Run setup-debootstrap.sh
        run: |
          sudo chmod +x setup-debootstrap.sh
          sudo bash -x setup-debootstrap.sh --arch amd64
          OUTPUT=$(sudo find "./build/amd64/" -maxdepth 1 -name "*.tar.gz" | grep -q -H 'debian-rootfs-amd64-')
          echo "OUTPUT=$(echo $OUTPUT)" >> $GITHUB_ENV

      - name: Upload debian-rootfs
        uses: actions/upload-artifact@v2
        with:
          name: debian-rootfs-${{ github.event.inputs.arch }}
          path: $OUTPUT
